settings:
  name: Azure Blob storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"

sidebar:
  entries:
    - title: Azure Blob storage docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: View your Azure Blob storage accounts
          url: /task-view-azure-blob-storage.html
    - title: Manage Azure Blob storage accounts
      entries:
        - title: Add new storage accounts
          url: /task-add-blob-storage.html
        - title: Change storage accounts settings
          url: /task-change-blob-storage-settings.html
        - title: Use NetApp data services with Azure Blob storage
          url: /task-blob-enable-data-services.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Storage Management
  repo: storage-management-family
